// <auto-generated />
using System;
using Global_College.mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Global_College.mvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409015049_FixPendingModelChanges")]
    partial class FixPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Global_College.domain.Models.Administrator.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "City Centre",
                            Name = "Dublin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Main Street",
                            Name = "Cork"
                        },
                        new
                        {
                            Id = 3,
                            Address = "West District",
                            Name = "Galway"
                        });
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.BranchCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("BranchId", "CourseId")
                        .IsUnique();

                    b.ToTable("BranchCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            CourseId = 2
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 2,
                            CourseId = 1
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            CourseId = 3
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 3,
                            CourseId = 4
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 3,
                            CourseId = 5
                        });
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateOnly(2025, 12, 31),
                            Name = "Computer Science",
                            StartDate = new DateOnly(2025, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateOnly(2025, 12, 31),
                            Name = "Business",
                            StartDate = new DateOnly(2025, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateOnly(2025, 12, 31),
                            Name = "Engineering",
                            StartDate = new DateOnly(2025, 1, 1)
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateOnly(2025, 12, 31),
                            Name = "Design",
                            StartDate = new DateOnly(2025, 1, 1)
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateOnly(2025, 12, 31),
                            Name = "Marketing",
                            StartDate = new DateOnly(2025, 1, 1)
                        });
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.CourseEnrolment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchCourseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EnrolDate")
                        .HasColumnType("date");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastChangeJustification")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StoppedDate")
                        .HasColumnType("date");

                    b.Property<int>("StudentProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchCourseId");

                    b.HasIndex("StudentProfileId", "BranchCourseId")
                        .IsUnique();

                    b.ToTable("CourseEnrolments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchCourseId = 1,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            BranchCourseId = 2,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 2
                        },
                        new
                        {
                            Id = 3,
                            BranchCourseId = 3,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 3
                        },
                        new
                        {
                            Id = 4,
                            BranchCourseId = 4,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 4
                        },
                        new
                        {
                            Id = 5,
                            BranchCourseId = 5,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 5
                        },
                        new
                        {
                            Id = 6,
                            BranchCourseId = 6,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 6
                        },
                        new
                        {
                            Id = 7,
                            BranchCourseId = 1,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 7
                        },
                        new
                        {
                            Id = 8,
                            BranchCourseId = 2,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 8
                        },
                        new
                        {
                            Id = 9,
                            BranchCourseId = 3,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 9
                        },
                        new
                        {
                            Id = 10,
                            BranchCourseId = 4,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 10
                        },
                        new
                        {
                            Id = 11,
                            BranchCourseId = 5,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 11
                        },
                        new
                        {
                            Id = 12,
                            BranchCourseId = 6,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 12
                        },
                        new
                        {
                            Id = 13,
                            BranchCourseId = 1,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 13
                        },
                        new
                        {
                            Id = 14,
                            BranchCourseId = 2,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 14
                        },
                        new
                        {
                            Id = 15,
                            BranchCourseId = 3,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 15
                        },
                        new
                        {
                            Id = 16,
                            BranchCourseId = 4,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 16
                        },
                        new
                        {
                            Id = 17,
                            BranchCourseId = 5,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 17
                        },
                        new
                        {
                            Id = 18,
                            BranchCourseId = 6,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 18
                        },
                        new
                        {
                            Id = 19,
                            BranchCourseId = 1,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 19
                        },
                        new
                        {
                            Id = 20,
                            BranchCourseId = 2,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 20
                        },
                        new
                        {
                            Id = 21,
                            BranchCourseId = 3,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 21
                        },
                        new
                        {
                            Id = 22,
                            BranchCourseId = 4,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 22
                        },
                        new
                        {
                            Id = 23,
                            BranchCourseId = 5,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 23
                        },
                        new
                        {
                            Id = 24,
                            BranchCourseId = 6,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 24
                        },
                        new
                        {
                            Id = 25,
                            BranchCourseId = 1,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 25
                        },
                        new
                        {
                            Id = 26,
                            BranchCourseId = 2,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 26
                        },
                        new
                        {
                            Id = 27,
                            BranchCourseId = 3,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 27
                        },
                        new
                        {
                            Id = 28,
                            BranchCourseId = 4,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 28
                        },
                        new
                        {
                            Id = 29,
                            BranchCourseId = 5,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 29
                        },
                        new
                        {
                            Id = 30,
                            BranchCourseId = 6,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 30
                        },
                        new
                        {
                            Id = 31,
                            BranchCourseId = 1,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 31
                        },
                        new
                        {
                            Id = 32,
                            BranchCourseId = 2,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 32
                        },
                        new
                        {
                            Id = 33,
                            BranchCourseId = 3,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 33
                        },
                        new
                        {
                            Id = 34,
                            BranchCourseId = 4,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 34
                        },
                        new
                        {
                            Id = 35,
                            BranchCourseId = 5,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 35
                        },
                        new
                        {
                            Id = 36,
                            BranchCourseId = 6,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 36
                        },
                        new
                        {
                            Id = 37,
                            BranchCourseId = 1,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 37
                        },
                        new
                        {
                            Id = 38,
                            BranchCourseId = 2,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 38
                        },
                        new
                        {
                            Id = 39,
                            BranchCourseId = 3,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 39
                        },
                        new
                        {
                            Id = 40,
                            BranchCourseId = 4,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 40
                        },
                        new
                        {
                            Id = 41,
                            BranchCourseId = 5,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 41
                        },
                        new
                        {
                            Id = 42,
                            BranchCourseId = 6,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 42
                        },
                        new
                        {
                            Id = 43,
                            BranchCourseId = 1,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 43
                        },
                        new
                        {
                            Id = 44,
                            BranchCourseId = 2,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 44
                        },
                        new
                        {
                            Id = 45,
                            BranchCourseId = 3,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 45
                        },
                        new
                        {
                            Id = 46,
                            BranchCourseId = 4,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 46
                        },
                        new
                        {
                            Id = 47,
                            BranchCourseId = 5,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 47
                        },
                        new
                        {
                            Id = 48,
                            BranchCourseId = 6,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 48
                        },
                        new
                        {
                            Id = 49,
                            BranchCourseId = 1,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 49
                        },
                        new
                        {
                            Id = 50,
                            BranchCourseId = 2,
                            EnrolDate = new DateOnly(2025, 1, 1),
                            Status = "Enrolled",
                            StudentProfileId = 50
                        });
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.CourseEnrolmentChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseEnrolmentId")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CourseEnrolmentId");

                    b.ToTable("CourseEnrolmentChangeHistories");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.FacultyCourseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchCourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("FacultyProfileId", "BranchCourseId")
                        .IsUnique();

                    b.ToTable("FacultyCourseAssignments");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.FacultyCourseAssignmentChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CourseStartDate")
                        .HasColumnType("date");

                    b.Property<int>("FacultyProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyProfileId");

                    b.ToTable("FacultyCourseAssignmentChangeHistories");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.FacultyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FacultyProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty1@college.com",
                            FacultyNumber = "00001",
                            FullName = "Faculty 1",
                            IdentityUserId = "faculty00001",
                            Phone = "9999991",
                            SystemEmail = "00001@college.com",
                            SystemPassword = "00001@college.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty2@college.com",
                            FacultyNumber = "00002",
                            FullName = "Faculty 2",
                            IdentityUserId = "faculty00002",
                            Phone = "9999992",
                            SystemEmail = "00002@college.com",
                            SystemPassword = "00002@college.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty3@college.com",
                            FacultyNumber = "00003",
                            FullName = "Faculty 3",
                            IdentityUserId = "faculty00003",
                            Phone = "9999993",
                            SystemEmail = "00003@college.com",
                            SystemPassword = "00003@college.com"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty4@college.com",
                            FacultyNumber = "00004",
                            FullName = "Faculty 4",
                            IdentityUserId = "faculty00004",
                            Phone = "9999994",
                            SystemEmail = "00004@college.com",
                            SystemPassword = "00004@college.com"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty5@college.com",
                            FacultyNumber = "00005",
                            FullName = "Faculty 5",
                            IdentityUserId = "faculty00005",
                            Phone = "9999995",
                            SystemEmail = "00005@college.com",
                            SystemPassword = "00005@college.com"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty6@college.com",
                            FacultyNumber = "00006",
                            FullName = "Faculty 6",
                            IdentityUserId = "faculty00006",
                            Phone = "9999996",
                            SystemEmail = "00006@college.com",
                            SystemPassword = "00006@college.com"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty7@college.com",
                            FacultyNumber = "00007",
                            FullName = "Faculty 7",
                            IdentityUserId = "faculty00007",
                            Phone = "9999997",
                            SystemEmail = "00007@college.com",
                            SystemPassword = "00007@college.com"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty8@college.com",
                            FacultyNumber = "00008",
                            FullName = "Faculty 8",
                            IdentityUserId = "faculty00008",
                            Phone = "9999998",
                            SystemEmail = "00008@college.com",
                            SystemPassword = "00008@college.com"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty9@college.com",
                            FacultyNumber = "00009",
                            FullName = "Faculty 9",
                            IdentityUserId = "faculty00009",
                            Phone = "9999999",
                            SystemEmail = "00009@college.com",
                            SystemPassword = "00009@college.com"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faculty10@college.com",
                            FacultyNumber = "00010",
                            FullName = "Faculty 10",
                            IdentityUserId = "faculty00010",
                            Phone = "99999910",
                            SystemEmail = "00010@college.com",
                            SystemPassword = "00010@college.com"
                        });
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SystemEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address 1",
                            Email = "student1@college.com",
                            FullName = "Student 1",
                            IdentityUserId = "student-user-1",
                            Phone = "0000001",
                            StudentNumber = "S0001",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address 2",
                            Email = "student2@college.com",
                            FullName = "Student 2",
                            IdentityUserId = "student-user-2",
                            Phone = "0000002",
                            StudentNumber = "S0002",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address 3",
                            Email = "student3@college.com",
                            FullName = "Student 3",
                            IdentityUserId = "student-user-3",
                            Phone = "0000003",
                            StudentNumber = "S0003",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address 4",
                            Email = "student4@college.com",
                            FullName = "Student 4",
                            IdentityUserId = "student-user-4",
                            Phone = "0000004",
                            StudentNumber = "S0004",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 5,
                            Address = "Address 5",
                            Email = "student5@college.com",
                            FullName = "Student 5",
                            IdentityUserId = "student-user-5",
                            Phone = "0000005",
                            StudentNumber = "S0005",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 6,
                            Address = "Address 6",
                            Email = "student6@college.com",
                            FullName = "Student 6",
                            IdentityUserId = "student-user-6",
                            Phone = "0000006",
                            StudentNumber = "S0006",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 7,
                            Address = "Address 7",
                            Email = "student7@college.com",
                            FullName = "Student 7",
                            IdentityUserId = "student-user-7",
                            Phone = "0000007",
                            StudentNumber = "S0007",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 8,
                            Address = "Address 8",
                            Email = "student8@college.com",
                            FullName = "Student 8",
                            IdentityUserId = "student-user-8",
                            Phone = "0000008",
                            StudentNumber = "S0008",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 9,
                            Address = "Address 9",
                            Email = "student9@college.com",
                            FullName = "Student 9",
                            IdentityUserId = "student-user-9",
                            Phone = "0000009",
                            StudentNumber = "S0009",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 10,
                            Address = "Address 10",
                            Email = "student10@college.com",
                            FullName = "Student 10",
                            IdentityUserId = "student-user-10",
                            Phone = "00000010",
                            StudentNumber = "S0010",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 11,
                            Address = "Address 11",
                            Email = "student11@college.com",
                            FullName = "Student 11",
                            IdentityUserId = "student-user-11",
                            Phone = "00000011",
                            StudentNumber = "S0011",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 12,
                            Address = "Address 12",
                            Email = "student12@college.com",
                            FullName = "Student 12",
                            IdentityUserId = "student-user-12",
                            Phone = "00000012",
                            StudentNumber = "S0012",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 13,
                            Address = "Address 13",
                            Email = "student13@college.com",
                            FullName = "Student 13",
                            IdentityUserId = "student-user-13",
                            Phone = "00000013",
                            StudentNumber = "S0013",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 14,
                            Address = "Address 14",
                            Email = "student14@college.com",
                            FullName = "Student 14",
                            IdentityUserId = "student-user-14",
                            Phone = "00000014",
                            StudentNumber = "S0014",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 15,
                            Address = "Address 15",
                            Email = "student15@college.com",
                            FullName = "Student 15",
                            IdentityUserId = "student-user-15",
                            Phone = "00000015",
                            StudentNumber = "S0015",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 16,
                            Address = "Address 16",
                            Email = "student16@college.com",
                            FullName = "Student 16",
                            IdentityUserId = "student-user-16",
                            Phone = "00000016",
                            StudentNumber = "S0016",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 17,
                            Address = "Address 17",
                            Email = "student17@college.com",
                            FullName = "Student 17",
                            IdentityUserId = "student-user-17",
                            Phone = "00000017",
                            StudentNumber = "S0017",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 18,
                            Address = "Address 18",
                            Email = "student18@college.com",
                            FullName = "Student 18",
                            IdentityUserId = "student-user-18",
                            Phone = "00000018",
                            StudentNumber = "S0018",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 19,
                            Address = "Address 19",
                            Email = "student19@college.com",
                            FullName = "Student 19",
                            IdentityUserId = "student-user-19",
                            Phone = "00000019",
                            StudentNumber = "S0019",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 20,
                            Address = "Address 20",
                            Email = "student20@college.com",
                            FullName = "Student 20",
                            IdentityUserId = "student-user-20",
                            Phone = "00000020",
                            StudentNumber = "S0020",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 21,
                            Address = "Address 21",
                            Email = "student21@college.com",
                            FullName = "Student 21",
                            IdentityUserId = "student-user-21",
                            Phone = "00000021",
                            StudentNumber = "S0021",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 22,
                            Address = "Address 22",
                            Email = "student22@college.com",
                            FullName = "Student 22",
                            IdentityUserId = "student-user-22",
                            Phone = "00000022",
                            StudentNumber = "S0022",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 23,
                            Address = "Address 23",
                            Email = "student23@college.com",
                            FullName = "Student 23",
                            IdentityUserId = "student-user-23",
                            Phone = "00000023",
                            StudentNumber = "S0023",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 24,
                            Address = "Address 24",
                            Email = "student24@college.com",
                            FullName = "Student 24",
                            IdentityUserId = "student-user-24",
                            Phone = "00000024",
                            StudentNumber = "S0024",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 25,
                            Address = "Address 25",
                            Email = "student25@college.com",
                            FullName = "Student 25",
                            IdentityUserId = "student-user-25",
                            Phone = "00000025",
                            StudentNumber = "S0025",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 26,
                            Address = "Address 26",
                            Email = "student26@college.com",
                            FullName = "Student 26",
                            IdentityUserId = "student-user-26",
                            Phone = "00000026",
                            StudentNumber = "S0026",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 27,
                            Address = "Address 27",
                            Email = "student27@college.com",
                            FullName = "Student 27",
                            IdentityUserId = "student-user-27",
                            Phone = "00000027",
                            StudentNumber = "S0027",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 28,
                            Address = "Address 28",
                            Email = "student28@college.com",
                            FullName = "Student 28",
                            IdentityUserId = "student-user-28",
                            Phone = "00000028",
                            StudentNumber = "S0028",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 29,
                            Address = "Address 29",
                            Email = "student29@college.com",
                            FullName = "Student 29",
                            IdentityUserId = "student-user-29",
                            Phone = "00000029",
                            StudentNumber = "S0029",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 30,
                            Address = "Address 30",
                            Email = "student30@college.com",
                            FullName = "Student 30",
                            IdentityUserId = "student-user-30",
                            Phone = "00000030",
                            StudentNumber = "S0030",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 31,
                            Address = "Address 31",
                            Email = "student31@college.com",
                            FullName = "Student 31",
                            IdentityUserId = "student-user-31",
                            Phone = "00000031",
                            StudentNumber = "S0031",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 32,
                            Address = "Address 32",
                            Email = "student32@college.com",
                            FullName = "Student 32",
                            IdentityUserId = "student-user-32",
                            Phone = "00000032",
                            StudentNumber = "S0032",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 33,
                            Address = "Address 33",
                            Email = "student33@college.com",
                            FullName = "Student 33",
                            IdentityUserId = "student-user-33",
                            Phone = "00000033",
                            StudentNumber = "S0033",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 34,
                            Address = "Address 34",
                            Email = "student34@college.com",
                            FullName = "Student 34",
                            IdentityUserId = "student-user-34",
                            Phone = "00000034",
                            StudentNumber = "S0034",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 35,
                            Address = "Address 35",
                            Email = "student35@college.com",
                            FullName = "Student 35",
                            IdentityUserId = "student-user-35",
                            Phone = "00000035",
                            StudentNumber = "S0035",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 36,
                            Address = "Address 36",
                            Email = "student36@college.com",
                            FullName = "Student 36",
                            IdentityUserId = "student-user-36",
                            Phone = "00000036",
                            StudentNumber = "S0036",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 37,
                            Address = "Address 37",
                            Email = "student37@college.com",
                            FullName = "Student 37",
                            IdentityUserId = "student-user-37",
                            Phone = "00000037",
                            StudentNumber = "S0037",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 38,
                            Address = "Address 38",
                            Email = "student38@college.com",
                            FullName = "Student 38",
                            IdentityUserId = "student-user-38",
                            Phone = "00000038",
                            StudentNumber = "S0038",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 39,
                            Address = "Address 39",
                            Email = "student39@college.com",
                            FullName = "Student 39",
                            IdentityUserId = "student-user-39",
                            Phone = "00000039",
                            StudentNumber = "S0039",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 40,
                            Address = "Address 40",
                            Email = "student40@college.com",
                            FullName = "Student 40",
                            IdentityUserId = "student-user-40",
                            Phone = "00000040",
                            StudentNumber = "S0040",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 41,
                            Address = "Address 41",
                            Email = "student41@college.com",
                            FullName = "Student 41",
                            IdentityUserId = "student-user-41",
                            Phone = "00000041",
                            StudentNumber = "S0041",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 42,
                            Address = "Address 42",
                            Email = "student42@college.com",
                            FullName = "Student 42",
                            IdentityUserId = "student-user-42",
                            Phone = "00000042",
                            StudentNumber = "S0042",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 43,
                            Address = "Address 43",
                            Email = "student43@college.com",
                            FullName = "Student 43",
                            IdentityUserId = "student-user-43",
                            Phone = "00000043",
                            StudentNumber = "S0043",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 44,
                            Address = "Address 44",
                            Email = "student44@college.com",
                            FullName = "Student 44",
                            IdentityUserId = "student-user-44",
                            Phone = "00000044",
                            StudentNumber = "S0044",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 45,
                            Address = "Address 45",
                            Email = "student45@college.com",
                            FullName = "Student 45",
                            IdentityUserId = "student-user-45",
                            Phone = "00000045",
                            StudentNumber = "S0045",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 46,
                            Address = "Address 46",
                            Email = "student46@college.com",
                            FullName = "Student 46",
                            IdentityUserId = "student-user-46",
                            Phone = "00000046",
                            StudentNumber = "S0046",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 47,
                            Address = "Address 47",
                            Email = "student47@college.com",
                            FullName = "Student 47",
                            IdentityUserId = "student-user-47",
                            Phone = "00000047",
                            StudentNumber = "S0047",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 48,
                            Address = "Address 48",
                            Email = "student48@college.com",
                            FullName = "Student 48",
                            IdentityUserId = "student-user-48",
                            Phone = "00000048",
                            StudentNumber = "S0048",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 49,
                            Address = "Address 49",
                            Email = "student49@college.com",
                            FullName = "Student 49",
                            IdentityUserId = "student-user-49",
                            Phone = "00000049",
                            StudentNumber = "S0049",
                            SystemEmail = "",
                            SystemPassword = ""
                        },
                        new
                        {
                            Id = 50,
                            Address = "Address 50",
                            Email = "student50@college.com",
                            FullName = "Student 50",
                            IdentityUserId = "student-user-50",
                            Phone = "00000050",
                            StudentNumber = "S0050",
                            SystemEmail = "",
                            SystemPassword = ""
                        });
                });

            modelBuilder.Entity("Global_College.domain.Models.Faculty.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Global_College.domain.Models.Faculty.AssignmentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StudentProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("AssignmentResults");
                });

            modelBuilder.Entity("Global_College.domain.Models.Faculty.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseEnrolmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Present")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourseEnrolmentId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("Global_College.domain.Models.Student.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<bool>("ResultsReleased")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Global_College.domain.Models.Student.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StudentProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.BranchCourse", b =>
                {
                    b.HasOne("Global_College.domain.Models.Administrator.Branch", "Branch")
                        .WithMany("BranchCourses")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Global_College.domain.Models.Administrator.Course", "Course")
                        .WithMany("BranchCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.CourseEnrolment", b =>
                {
                    b.HasOne("Global_College.domain.Models.Administrator.BranchCourse", "BranchCourse")
                        .WithMany("CourseEnrolments")
                        .HasForeignKey("BranchCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Global_College.domain.Models.Administrator.StudentProfile", "StudentProfile")
                        .WithMany("CourseEnrolments")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BranchCourse");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.CourseEnrolmentChangeHistory", b =>
                {
                    b.HasOne("Global_College.domain.Models.Administrator.CourseEnrolment", "CourseEnrolment")
                        .WithMany("ChangeHistories")
                        .HasForeignKey("CourseEnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseEnrolment");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.FacultyCourseAssignment", b =>
                {
                    b.HasOne("Global_College.domain.Models.Administrator.BranchCourse", "BranchCourse")
                        .WithMany()
                        .HasForeignKey("BranchCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Global_College.domain.Models.Administrator.Course", null)
                        .WithMany("FacultyCourseAssignments")
                        .HasForeignKey("CourseId");

                    b.HasOne("Global_College.domain.Models.Administrator.FacultyProfile", "FacultyProfile")
                        .WithMany("FacultyCourseAssignments")
                        .HasForeignKey("FacultyProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BranchCourse");

                    b.Navigation("FacultyProfile");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.FacultyCourseAssignmentChangeHistory", b =>
                {
                    b.HasOne("Global_College.domain.Models.Administrator.FacultyProfile", "FacultyProfile")
                        .WithMany("ChangeHistories")
                        .HasForeignKey("FacultyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyProfile");
                });

            modelBuilder.Entity("Global_College.domain.Models.Faculty.Assignment", b =>
                {
                    b.HasOne("Global_College.domain.Models.Administrator.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Global_College.domain.Models.Faculty.AssignmentResult", b =>
                {
                    b.HasOne("Global_College.domain.Models.Faculty.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Global_College.domain.Models.Administrator.StudentProfile", "StudentProfile")
                        .WithMany("AssignmentResults")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Global_College.domain.Models.Faculty.AttendanceRecord", b =>
                {
                    b.HasOne("Global_College.domain.Models.Administrator.CourseEnrolment", "CourseEnrolment")
                        .WithMany()
                        .HasForeignKey("CourseEnrolmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseEnrolment");
                });

            modelBuilder.Entity("Global_College.domain.Models.Student.Exam", b =>
                {
                    b.HasOne("Global_College.domain.Models.Administrator.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Global_College.domain.Models.Student.ExamResult", b =>
                {
                    b.HasOne("Global_College.domain.Models.Student.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Global_College.domain.Models.Administrator.StudentProfile", "StudentProfile")
                        .WithMany("ExamResults")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.Branch", b =>
                {
                    b.Navigation("BranchCourses");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.BranchCourse", b =>
                {
                    b.Navigation("CourseEnrolments");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("BranchCourses");

                    b.Navigation("Exams");

                    b.Navigation("FacultyCourseAssignments");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.CourseEnrolment", b =>
                {
                    b.Navigation("ChangeHistories");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.FacultyProfile", b =>
                {
                    b.Navigation("ChangeHistories");

                    b.Navigation("FacultyCourseAssignments");
                });

            modelBuilder.Entity("Global_College.domain.Models.Administrator.StudentProfile", b =>
                {
                    b.Navigation("AssignmentResults");

                    b.Navigation("CourseEnrolments");

                    b.Navigation("ExamResults");
                });
#pragma warning restore 612, 618
        }
    }
}
